name: Build [All]

on:
  workflow_dispatch:
  push:
    paths:
      - '1966/**.*'
      - '1965/**.*'
      - '1953/**.*'
      - '.github/workflows/compile-core.yml'
  pull_request:
  schedule:
    - cron: "0 15 * * 5"
#  repository_dispatch:
#    types: [Component_update]
    
    
jobs:
  build-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [1965, 1966, 1953]
    container: ps2dev/ps2dev:v1.0
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip p7zip
    - uses: actions/checkout@v2
    - run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --prune --unshallow
        
    - name: Compile
      run: |
        cd ${{ matrix.package }}
        SCH=${GITHUB_SHA::7}
        make FMCB_INSTALLER_VERSION=$SCH
        
    - name: Compile ps2link IRX
      run: |
        cd ps2link
        make
        ls
        
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"


    - name: Prepare folder for Release
      run: |
        cp Changelog.md ${{ matrix.package }}/__Package/Changelog.md
        DATEE=`date '+[%Y-%m-%d]'`
        VER=${{ matrix.package }}
        SCH=${GITHUB_SHA::7}
        cd ${{ matrix.package }}
        cp FMCBInstaller.elf __Package/
        cd __Package
        echo title=FMCBInst-$DATEE-$VER>title.cfg
        echo boot=FMCBInstaller.elf>>title.cfg
        cd lang
        echo $SCH >commit.txt
        cd ..
        cd ..
        cd ..
         
    - name: zip Folder For Release
      run: |
        VER=${{ matrix.package }}
        cd $VER
        cd __Package
        cd INSTALL
        cd ..
        cd ..
        DATEE=`date '+[%Y-%m-%d]'`
        mv __Package FMCBinst-$VER-$DATEE
        7z a -t7z -r FMCB-$VER.7z FMCBinst*/*
        
    - name: Upload artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.package }}
        path: |
            ${{ matrix.package }}/*.7z

 
  Release-packages:
    needs: build-packages
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest     
    steps:

      - name: Download 1.965 artifact
        uses: actions/download-artifact@v1
        with:
          name: 1965
          
      - name: Download 1.953 artifact
        uses: actions/download-artifact@v1
        with:
          name: 1953
          
      - name: Download 1.966 artifact
        uses: actions/download-artifact@v1
        with:
          name: 1966

      - name: Create release
        if: github.ref == 'refs/heads/master'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "FreeMcBoot"
          files: |
                1966/*.7z
                1965/*.7z
                1953/*.7z
